workflows:

    flutter-widget:
        name: Flutter Widget
        instance_type: linux_x2
        max_build_duration: 120
        environment:
            flutter: dev
        scripts:
            - curl ipinfo.io && lscpu && free -m && uptime
